services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.1-fpm-alpine
    volumes:
      - .:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=256M

  # 開発用のPHP環境（必要に応じて）
  php-dev:
    image: php:8.1-apache
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    profiles:
      - dev

volumes:
  web_data:
